# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('license_plate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bus_type', models.CharField(choices=[('AC', 'Air Conditioned'), ('DE', 'Deluxe'), ('EX', 'Express'), ('OR', 'Ordinary'), ('SM', 'Small')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('buses_that_stop_here', models.CharField(choices=[('A', 'All'), ('O', 'Ordinary')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(to='Buses.Stop'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Buses.Route'),
        ),
    ]
