# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0002_auto_20161013_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=20)),
                ('longitute', models.CharField(max_length=20)),
                ('passengers', models.IntegerField(verbose_name='Number of passengers')),
                ('license_plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buses.Bus')),
            ],
        ),
    ]
