# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 05:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0004_auto_20161013_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentlocation',
            old_name='longitute',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='locationhistory',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
